apiVersion: v1
kind: Service
metadata:
  name: gametoripanelservice
spec:
  selector:
    app: gametoripanelpod
  # type: NodePort # For NodePort Service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4201 # App will be accessable on the port 4201 of External IP
      targetPort: 80
      # nodePort: 30001 # App will be accessable from http://Master_Node_IP:300001 for NodePort Service
